version: "3.9"
services:
  server:
    container_name: ms_raflyanandas_betest_server
    environment:
      - PASS_SEC=699ygixgnj
      - JWT_ACCESS_SEC=bafpmlzYqS
      - MONGODB_URI=mongodb://root:root@mongo:27017/db_raflyanandas_betest?authSource=admin
      - REDIS_URI=redis://redis_raflyanandas_betest:6379
      - NODE_ENV=production
    restart: always
    build: .
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/usr/src/app
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=db_raflyanandas_betest
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis_raflyanandas_betest
    image: "redis:alpine"
    ports:
      - "6379:6379"
