const mongoose = require("mongoose");
const UserSchema = new mongoose.Schema(
  // Id field is auto generated by mongodb
  {
    userName: { type: String, required: true, unique: true },
    accountNumber: { type: Number, required: true, unique: true, index: true },
    emailAddress: { type: String, required: true, unique: true },
    identityNumber: { type: Number, required: true, unique: true, index: true },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Users", UserSchema);
