const API_VERSION = "v1";
const JWT_ACCESS_EXPIRATION = 7200; // 2 hour
const REDIS_DEFAULT_EXPIRATION = 3600; // 1 Hour

module.exports = {
  API_VERSION,
  JWT_ACCESS_EXPIRATION,
  REDIS_DEFAULT_EXPIRATION,
};
